// This file is auto-generated by @hey-api/openapi-ts

export const HealthResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
    },
  },
  type: "object",
  required: ["status"],
  title: "HealthResponse",
} as const;
