// This file is auto-generated by @hey-api/openapi-ts

export const CallerSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    username: {
      type: "string",
      title: "Username",
    },
    roles: {
      items: {
        $ref: "#/components/schemas/Role",
      },
      type: "array",
      uniqueItems: true,
      title: "Roles",
    },
  },
  type: "object",
  required: ["id", "username", "roles"],
  title: "Caller",
  description:
    "The actor on whose behalf a command runs.\n\nConstructed by app.framework.auth.current_user from the session lookup.\nPassed to Dispatcher.dispatch and consumed by ADR-0047 authorization\npredicates. Frozen so callers cannot be mutated mid-pipeline.",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HealthResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
    },
  },
  type: "object",
  required: ["status"],
  title: "HealthResponse",
} as const;

export const LoginRequestSchema = {
  properties: {
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "LoginRequest",
} as const;

export const RoleSchema = {
  type: "string",
  enum: ["superadmin", "admin", "coordinator", "auditor"],
  title: "Role",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
