// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HealthResponse
 */
export type HealthResponse = {
  /**
   * Status
   */
  status: string;
};

export type HealthcheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthcheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type HealthcheckHealthGetResponse =
  HealthcheckHealthGetResponses[keyof HealthcheckHealthGetResponses];
