/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminContractsIndexRouteImport } from './routes/_authenticated/admin/contracts/index'
import { Route as AuthenticatedAdminContractsNewRouteImport } from './routes/_authenticated/admin/contracts/new'
import { Route as AuthenticatedAdminContractsContractIdRouteImport } from './routes/_authenticated/admin/contracts/$contractId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsIndexRoute =
  AuthenticatedAdminContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsNewRoute =
  AuthenticatedAdminContractsNewRouteImport.update({
    id: '/contracts/new',
    path: '/contracts/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsContractIdRoute =
  AuthenticatedAdminContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/admin/contracts/new': typeof AuthenticatedAdminContractsNewRoute
  '/admin/contracts/': typeof AuthenticatedAdminContractsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/admin/contracts/new': typeof AuthenticatedAdminContractsNewRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/_authenticated/admin/contracts/new': typeof AuthenticatedAdminContractsNewRoute
  '/_authenticated/admin/contracts/': typeof AuthenticatedAdminContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/contracts/$contractId'
    | '/admin/contracts/new'
    | '/admin/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/contracts/$contractId'
    | '/admin/contracts/new'
    | '/admin/contracts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/contracts/$contractId'
    | '/_authenticated/admin/contracts/new'
    | '/_authenticated/admin/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts/': {
      id: '/_authenticated/admin/contracts/'
      path: '/contracts'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof AuthenticatedAdminContractsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts/new': {
      id: '/_authenticated/admin/contracts/new'
      path: '/contracts/new'
      fullPath: '/admin/contracts/new'
      preLoaderRoute: typeof AuthenticatedAdminContractsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contracts/$contractId': {
      id: '/_authenticated/admin/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/admin/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedAdminContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminContractsContractIdRoute: typeof AuthenticatedAdminContractsContractIdRoute
  AuthenticatedAdminContractsNewRoute: typeof AuthenticatedAdminContractsNewRoute
  AuthenticatedAdminContractsIndexRoute: typeof AuthenticatedAdminContractsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminContractsContractIdRoute:
    AuthenticatedAdminContractsContractIdRoute,
  AuthenticatedAdminContractsNewRoute: AuthenticatedAdminContractsNewRoute,
  AuthenticatedAdminContractsIndexRoute: AuthenticatedAdminContractsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
