"""history_infrastructure

Revision ID: b555ac8d13da
Revises: 0377af236b82
Create Date: 2026-05-19 10:12:56.765295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b555ac8d13da'
down_revision: Union[str, Sequence[str], None] = '0377af236b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_audit_log',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('payload_summary', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_command_audit_log_command_id', 'command_audit_log', ['command_id'], unique=False)
    op.create_index('ix_command_audit_log_type_entity_at', 'command_audit_log', ['entity_type', 'entity_id', 'at'], unique=False)
    op.create_table('contractor_engagement_history',
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('transition_name', sa.String(), nullable=False),
    sa.Column('state_context', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contractor_engagement_history_entity_id_at', 'contractor_engagement_history', ['entity_id', 'at'], unique=False)
    op.create_table('deliverable_history',
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('transition_name', sa.String(), nullable=False),
    sa.Column('state_context', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliverable_history_entity_id_at', 'deliverable_history', ['entity_id', 'at'], unique=False)
    op.create_table('document_history',
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_history_entity_id_at', 'document_history', ['entity_id', 'at'], unique=False)
    op.create_table('employee_role_history',
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('transition_name', sa.String(), nullable=False),
    sa.Column('state_context', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employee_role_history_entity_id_at', 'employee_role_history', ['entity_id', 'at'], unique=False)
    op.create_table('project_history',
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('transition_name', sa.String(), nullable=False),
    sa.Column('state_context', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_history_entity_id_at', 'project_history', ['entity_id', 'at'], unique=False)
    op.create_table('rfa_history',
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfa_history_entity_id_at', 'rfa_history', ['entity_id', 'at'], unique=False)
    op.create_table('sample_batch_history',
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('transition_name', sa.String(), nullable=False),
    sa.Column('state_context', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sample_batch_history_entity_id_at', 'sample_batch_history', ['entity_id', 'at'], unique=False)
    op.create_table('wa_code_history',
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('transition_name', sa.String(), nullable=False),
    sa.Column('state_context', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wa_code_history_entity_id_at', 'wa_code_history', ['entity_id', 'at'], unique=False)
    op.create_table('wa_history',
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('caller_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wa_history_entity_id_at', 'wa_history', ['entity_id', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wa_history_entity_id_at', table_name='wa_history')
    op.drop_table('wa_history')
    op.drop_index('ix_wa_code_history_entity_id_at', table_name='wa_code_history')
    op.drop_table('wa_code_history')
    op.drop_index('ix_sample_batch_history_entity_id_at', table_name='sample_batch_history')
    op.drop_table('sample_batch_history')
    op.drop_index('ix_rfa_history_entity_id_at', table_name='rfa_history')
    op.drop_table('rfa_history')
    op.drop_index('ix_project_history_entity_id_at', table_name='project_history')
    op.drop_table('project_history')
    op.drop_index('ix_employee_role_history_entity_id_at', table_name='employee_role_history')
    op.drop_table('employee_role_history')
    op.drop_index('ix_document_history_entity_id_at', table_name='document_history')
    op.drop_table('document_history')
    op.drop_index('ix_deliverable_history_entity_id_at', table_name='deliverable_history')
    op.drop_table('deliverable_history')
    op.drop_index('ix_contractor_engagement_history_entity_id_at', table_name='contractor_engagement_history')
    op.drop_table('contractor_engagement_history')
    op.drop_index('ix_command_audit_log_type_entity_at', table_name='command_audit_log')
    op.drop_index('ix_command_audit_log_command_id', table_name='command_audit_log')
    op.drop_table('command_audit_log')
    # ### end Alembic commands ###
