// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  healthcheckHealthGet,
  loginAuthLoginPost,
  logoutAuthLogoutPost,
  meAuthMeGet,
  type Options,
} from "../sdk.gen";
import type {
  HealthcheckHealthGetData,
  HealthcheckHealthGetResponse,
  LoginAuthLoginPostData,
  LoginAuthLoginPostError,
  LoginAuthLoginPostResponse,
  LogoutAuthLogoutPostData,
  LogoutAuthLogoutPostError,
  LogoutAuthLogoutPostResponse,
  MeAuthMeGetData,
  MeAuthMeGetError,
  MeAuthMeGetResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthcheckHealthGetQueryKey = (options?: Options<HealthcheckHealthGetData>) =>
  createQueryKey("healthcheckHealthGet", options);

/**
 * Healthcheck
 */
export const healthcheckHealthGetOptions = (options?: Options<HealthcheckHealthGetData>) =>
  queryOptions<
    HealthcheckHealthGetResponse,
    DefaultError,
    HealthcheckHealthGetResponse,
    ReturnType<typeof healthcheckHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthcheckHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthcheckHealthGetQueryKey(options),
  });

/**
 * Login
 */
export const loginAuthLoginPostMutation = (
  options?: Partial<Options<LoginAuthLoginPostData>>,
): UseMutationOptions<
  LoginAuthLoginPostResponse,
  LoginAuthLoginPostError,
  Options<LoginAuthLoginPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginAuthLoginPostResponse,
    LoginAuthLoginPostError,
    Options<LoginAuthLoginPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await loginAuthLoginPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout
 *
 * Revoke the session row and clear the cookie. Works even when the
 * session has already expired (cookie just gets cleared).
 */
export const logoutAuthLogoutPostMutation = (
  options?: Partial<Options<LogoutAuthLogoutPostData>>,
): UseMutationOptions<
  LogoutAuthLogoutPostResponse,
  LogoutAuthLogoutPostError,
  Options<LogoutAuthLogoutPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LogoutAuthLogoutPostResponse,
    LogoutAuthLogoutPostError,
    Options<LogoutAuthLogoutPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logoutAuthLogoutPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const meAuthMeGetQueryKey = (options?: Options<MeAuthMeGetData>) =>
  createQueryKey("meAuthMeGet", options);

/**
 * Me
 */
export const meAuthMeGetOptions = (options?: Options<MeAuthMeGetData>) =>
  queryOptions<
    MeAuthMeGetResponse,
    MeAuthMeGetError,
    MeAuthMeGetResponse,
    ReturnType<typeof meAuthMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await meAuthMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: meAuthMeGetQueryKey(options),
  });
